// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfVc4PtHqfgFxmdDqaNllrcqrY1Nk5AE',
    appId: '1:521288497698:web:0c5f6f6968b819479aa87b',
    messagingSenderId: '521288497698',
    projectId: 'smartpark1001-92c6b',
    authDomain: 'smartpark1001-92c6b.firebaseapp.com',
    storageBucket: 'smartpark1001-92c6b.firebasestorage.app',
    measurementId: 'G-DSGEZ9Q7HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPr7Pdzr16ht7LJUUqtyxWLwxwwUJklxY',
    appId: '1:521288497698:android:08af539f728505ed9aa87b',
    messagingSenderId: '521288497698',
    projectId: 'smartpark1001-92c6b',
    storageBucket: 'smartpark1001-92c6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDQfab5bKjDBY_KuayN5s_mrdmZtfcFXs',
    appId: '1:521288497698:ios:829ed262258299c19aa87b',
    messagingSenderId: '521288497698',
    projectId: 'smartpark1001-92c6b',
    storageBucket: 'smartpark1001-92c6b.firebasestorage.app',
    iosBundleId: 'com.campuspark.campusPark',
  );
}
